title: "Namasi G. Sankar"
name: "Namasi G. Sankar"
position: "PhD Student in Quantum Computing"
affiliation: "University College Dublin"

author:
  name: "Namasi G. Sankar"
  avatar : "bio-photo.jpg" # Path to your uploaded image
  bio: "Doctoral Candidate | Quantum Computing and Optimisation | Genomics"
  location: "University College Dublin, Ireland"
  email: "namasivayam.gomathisankar@ucdconnect.ie"
  github: "Namasi-PhD"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=WMRJjRkAAAAJ"




defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

email: "namasivayam.gomathisankar@ucdconnect.ie"
github_username: "Namasi-PhD"

description: >
  PhD researcher working on scalable quantum optimisation,
  HADOF framework, and applications in genomics.

url: "https://Namasi-PhD.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _pages
