title: "Namasi G. Sankar"
name: "Namasi G. Sankar"
position: "PhD Student in Quantum Computing"
affiliation: "University College Dublin"

author:
  name   : "Namasi G. Sankar"
  avatar : "images/profile.jpg" # Path to your uploaded image
  bio    : "PhD Student in Quantum Computing"
  location: "Dublin, Ireland"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Namasi-PhD"

email: "namasivayam.gomathisankar@ucdconnect.ie"
github_username: "yourusername"

description: >
  PhD researcher working on scalable quantum optimisation,
  HADOF framework, and applications in genomics.

url: "https://Namasi-PhD.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _pages
